ETFOPortal/Areas/DocumentLocker/Controllers/DocumentLockerController.cs
using System;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Adxstudio.Xrm.Web.Mvc;
using Microsoft.Xrm.Portal.Configuration;
using Site.Library;
using Site.Helpers;
using Xrm;

namespace Site.Areas.DocumentLocker.Controllers
{
    [PortalView]
    [Authorize]
    public class DocumentLockerController : Controller
    {
        private Contact Contact
        {
            get { return PortalCrmConfigurationManager.CreatePortalContext().User as Contact; }
        }

        //[ChildActionOnly]
        public ActionResult Index()
        {
            var annotations = AnnotationsHelper.GetAnnotations(Contact.Id, true); 
            CurrentUser.ProfileDocumentsCount = annotations.Count;
            CurrentUser.ProfileDocumentsSize = annotations.Sum(a => a.FileSize ?? 0);

            ViewBag.ProfileDocumentsCount = CurrentUser.ProfileDocumentsCount;
            ViewBag.ProfileDocumentsSize = CurrentUser.ProfileDocumentsSize;

            return View(annotations);
        }

        [HttpPost]
        public JsonResult UploadDocument(string description)
        {
            const int mbbytes = 1024000;
            var totalSize = Convert.ToInt32(ConfigurationManager.AppSettings["Document.Locker.Max.Files.Size"]);
            var totalCount = Convert.ToInt32(ConfigurationManager.AppSettings["Document.Locker.Max.Files.Count"]);

            if (CurrentUser.ProfileDocumentsSize == null || CurrentUser.ProfileDocumentsCount == null)
            {
                return Json(new { Success = false, Refresh = true });
            }

            if (Request.Files["file"] != null)
            {
                var file = Request.Files["file"];

                //Validate size
                var maxSize = Convert.ToInt32(ConfigurationManager.AppSettings["Document.Locker.Max.File.Size"]);
                var mb = 0;

                if (file.ContentLength > 0 && file.ContentLength <= maxSize)
                {
                    if (CurrentUser.ProfileDocumentsCount.Value + 1 > totalCount || CurrentUser.ProfileDocumentsSize.Value + file.ContentLength > totalSize)
                    {
                        mb = totalSize / mbbytes;
                        return Json(new { Success = false, Message = String.Format("It is not possible to upload the document. You can upload maximum {0} documents and all of them must have a maximum size of {1}MB", totalCount, mb) });
                    }

                    var extension = Path.GetExtension(file.FileName);
                    var mimetype = MimeTypeHelper.GetMimeTypeFromExtension(extension);
                    var output = new byte[file.InputStream.Length];
                    file.InputStream.Read(output, 0, output.Length);

                    var annotation = new Annotation()
                    {
                        FileName = file.FileName,
                        //FileSize = file.ContentLength,
                        IsDocument = true,
                        DocumentBody = Convert.ToBase64String(output),
                        MimeType = mimetype,
                        Subject = description
                    };
                    
                    AnnotationsHelper.CreateAnnotation(annotation, Contact);
                    var cannotation = new CustomAnnotation()
                    {
                        Id = annotation.Id,
                        AnnotationId = annotation.AnnotationId,
                        FileName = annotation.FileName,
                        FileSize = file.ContentLength,
                        IsDocument = annotation.IsDocument,
                        //DocumentBody = annotation.DocumentBody,
                        MimeType = annotation.MimeType,
                        Subject = annotation.Subject
                    };

                    CurrentUser.ProfileDocumentsCount++;
                    CurrentUser.ProfileDocumentsSize += file.ContentLength;

                    return Json(new { Success = true, Document = cannotation });
                }

                mb = maxSize / mbbytes;
                return Json(new { Success = false, Message = String.Format("Document should be {0}MB maximum, please pick up a different document from your computer and try again", mb) });
            }

            return Json(new {Success = false, NoFileSent = true, Message = "No file was uploaded, please pick up a file from your computer and try again"});
        }

        public JsonResult DeleteDocument(Guid id)
        {
            if (CurrentUser.ProfileDocumentsSize == null || CurrentUser.ProfileDocumentsCount == null)
            {
                return Json(new { Success = false, Refresh = true });
            }

            var size = AnnotationsHelper.GetAnnotationFileSize(id);
            AnnotationsHelper.DeleteAnnotation(id);

            CurrentUser.ProfileDocumentsCount--;
            CurrentUser.ProfileDocumentsSize -= size;

            return Json(new { Success = true });
        }

        [HttpPost, FileDownload]
        public FileResult DownloadDocument(Guid id)
        {
            var fileName = "";
            var mimetype = "";
            var document = AnnotationsHelper.GetAnnotationDocumentBody(id, out fileName, out mimetype);

            if (document == null || document.Length == 0)
            {
                throw new Exception("There is a problem downloading the file, it may not exists anymore");
            }

            return File(document, mimetype, fileName);
        }
    }
}

ETFOPortal/Areas/DocumentLocker/Views/DocumentLocker/Index.cshtml
@using System.Configuration
@using Newtonsoft.Json
@using Adxstudio.Xrm.Web.Mvc.Html
@model List<Site.Library.CustomAnnotation>
@{
    const int mbbytes = 1024000;
    var maxSize = 1.0 * Convert.ToInt32(ConfigurationManager.AppSettings["Document.Locker.Max.File.Size"]) / mbbytes;
    var totalSize = 1.0 * Convert.ToInt32(ConfigurationManager.AppSettings["Document.Locker.Max.Files.Size"]) / mbbytes;
    var totalCount = Convert.ToInt32(ConfigurationManager.AppSettings["Document.Locker.Max.Files.Count"]);
}

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
<link rel="stylesheet" href="~/css/jquery-file-upload/jquery.fileupload.css">

<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">@(Html.SnippetLiteral("DocumentLocker/MyDocuments", "My Documents"))</h4>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-12" data-bind="visible: isUploadEnabled()" style="display: none;">
                <form id="document-locker-upload-form" role="form" method="POST" enctype="multipart/form-data">
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <p>
                            @(String.Format(Html.SnippetLiteral("DocumentLocker/Introduction", "In this section you can manage your ETFO documents. You can upload maximum {0} documents and all your documents must have a maximum size of {1}MB. Also each document you upload must be {2}MB maximum."), totalCount, totalSize.ToString("N2"), maxSize.ToString("N2")))
                        </p>
                        <hr/>
                    </div>
                    <div class="form-group">
                        <label>@(Html.SnippetLiteral("DocumentLocker/Description", "Description"))</label>
                        <input type="text" class="form-control" name="description" placeholder="Enter a description">
                    </div>
                    <div class="form-group">
                        <label>@(Html.SnippetLiteral("DocumentLocker/Document", "Document"))</label>
                        <br/>
                        <span class="btn btn-success fileinput-button">
                            <i class="fa fa-plus"></i>
                            <span>@(Html.SnippetLiteral("DocumentLocker/SelectFile", "Select a file"))</span>
                            <input type="file" name="file" />
                        </span>
                        <span class="selected-file" style="display: none;"></span>
                    </div>
                    <button type="submit" id="upload-tg" class="btn btn-primary pull-right">@(Html.SnippetLiteral("DocumentLocker/Submit", "Submit"))</button>
                    <p class="clearfix"></p>
                </form>
            </div>
    
            <div class="col-md-12" data-bind="visible: isUploadEnabled()" style="display: none;">
                <div id="dlprogress" class="progress">
                    <div class="progress-bar progress-bar-success"></div>
                </div>
            </div>
            
            <div class="col-md-12" data-bind="visible: !isUploadEnabled()" style="display: none;">
                <p>
                    @(Html.SnippetLiteral("DocumentLocker/MaximumDocumentReached", "You have reached the maximum number of documents allowed. To upload a new document you must delete an existing one."))
                </p>
                <hr/>
            </div>
    
            <div class="col-md-12">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <td>@(Html.SnippetLiteral("DocumentLocker/FileName", "File Name"))</td>
                            <td>@(Html.SnippetLiteral("DocumentLocker/Description", "Description"))</td>
                            <td>@(Html.SnippetLiteral("DocumentLocker/Type", "Type"))</td>
                            <td>@(Html.SnippetLiteral("DocumentLocker/SizeMB", "Size (MB)"))</td>
                            <td>@(Html.SnippetLiteral("DocumentLocker/Actions", "Actions"))</td>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- ko foreach: data -->
                        <tr>
                            <td data-bind="text: FileName"></td>
                            <td data-bind="text: Subject"></td>
                            <td data-bind="text: MimeType"></td>
                            <td data-bind="documentSize: FileSize"></td>
                            <td>
                                <a class="download-tg" href="javascript:void(0);" data-bind="click: $parent.downloadDocument"><i class="fa fa-cloud-download"></i></a>
                                <a class="delete-tg" href="javascript:void(0);" data-bind="click: $parent.deleteDocument"><i class="fa fa-trash-o"></i></a>
                            </td>
                        </tr>
                        <!-- /ko -->
                        <tr>
                            <td colspan="5" data-bind="text: getTotalText" align="right"></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
    
@Html.Partial("_Modals")

<script src="//ajax.aspnetcdn.com/ajax/jQuery/jquery-1.9.1.min.js"> </script>
<script src="//ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"> </script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/knockout/3.2.0/knockout-min.js"> </script>
<script src="//cdnjs.cloudflare.com/ajax/libs/knockout.mapping/2.4.1/knockout.mapping.js"> </script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js"> </script>
<script src="//ajax.aspnetcdn.com/ajax/mvc/5.1/jquery.validate.unobtrusive.js"> </script>
<script src="//cdnjs.cloudflare.com/ajax/libs/underscore.js/1.6.0/underscore-min.js"></script>
<script src="~/js/jquery-file-upload/vendor/jquery.ui.widget.js"></script>
<script src="~/js/jquery-file-upload/jquery.iframe-transport.js"></script>
<script src="~/js/jquery-file-upload/jquery.fileupload.js"></script>
<script src="~/js/jquery.fileDownload.js"></script>
<script src="~/js/iframeResizer.contentWindow.js"></script>
<script src="~/js/ETFO/ajax.update.progress.js"></script>
<script src="~/js/ETFO/etfo.js"></script>
<script src="~/js/document.locker.js"></script>
<script type="text/javascript">
    $(function () {
        var options =
        {
            maxDocuments: @(totalCount),
            documents: @(Html.Raw(JsonConvert.SerializeObject(Model))),
            uploadUrl: '@Url.Action("UploadDocument", "DocumentLocker")',
            deleteUrl: '@Url.Action("DeleteDocument", "DocumentLocker")',
            downloadUrl: '@Url.Action("DownloadDocument", "DocumentLocker")',
            maxSize: parseInt('@(ConfigurationManager.AppSettings["Document.Locker.Max.File.Size"])'),
            texts:
            {
                modalTitle: '@(Html.SnippetLiteral("DocumentLocker/ModalTitle", "ETFO Document Locker"))',
                totalFiles: '@(Html.SnippetLiteral("DocumentLocker/TotalFiles", "Total Files"))',
                totalSizeMb: '@(Html.SnippetLiteral("DocumentLocker/TotalSizeMB", "Total Size (MB)"))',
                areYouSureFile: '@(Html.SnippetLiteral("DocumentLocker/AreYouSureDelete", "Are you sure you want to delete this file?"))',
                yes: '@(Html.SnippetLiteral("DocumentLocker/Yes", "Yes"))',
                no: '@(Html.SnippetLiteral("DocumentLocker/No", "No"))',
                errorDeleteting: '@(Html.SnippetLiteral("DocumentLocker/ErrorDeleting", "It was not possible to delete your document. Please try again"))',
                errorDownloading: '@(Html.SnippetLiteral("DocumentLocker/ErrorDownloading", "There is a problem downloading the file, it may not exists anymore"))',
                documentZeroSize: '@(Html.SnippetLiteral("DocumentLocker/FileZeroSize", "The document you want to upload is empty or has zero bytes. Please select another one."))',
                documentTooBig: '@(Html.SnippetLiteral("DocumentLocker/FileTooBig", "The document you want to upload is too big, the maximum size allowed per document is {0}MB. Please select another one."))',
                selectDocument: '@(Html.SnippetLiteral("DocumentLocker/SelectAFileToUpload", "Please select a file to upload"))',
            }
        };
        documentlocker.load(options);
    });
</script>