ETFOPortal/Areas/Payment/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using DotNetOpenAuth.Messaging;
using Microsoft.Xrm.Sdk;
using Site.Areas.Payment.Library;
//using Xrm;

namespace Site.Areas.Payment.Models
{
    [Serializable]
    public class ShoppingCart
    {
        public string OrderId { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalTax { get; set; }
        public decimal Deferral { get; set; }
        public decimal Due { get; set; }
        public decimal TaxPending { get; set; }
        public decimal TotalToPay { get; set; }
        public bool IsAsyncRequest { get; set; }
        
        public CreditCardInfo CreditCard { get; set; }
        public Dictionary<Guid, ShoppingCartDetail> Details { get; set; }

        public ShoppingCart()
        {
            Details = new Dictionary<Guid, ShoppingCartDetail>();
        }
    }

    [Serializable]
    public class ShoppingCartDetail
    {
        public EventShopingCart Event;
        public BillingService.PaymentInfo PaymentInfo;
    }

    [Serializable]
    public class CreditCardInfo
    {
        public string TransactionID { get; set; }
        public string TransactionType { get; set; }
        public string DateandTime { get; set; }
        public string PaymentAmount { get; set; }
        public string AuthorizationCode { get; set; }
        public string ResponseCode { get; set; }
        public string ISOCode { get; set; }
        public string Message { get; set; }
        public string ReferenceNumber { get; set; }
        public string NameOnTheCard { get; set; }
        public string CreditCardNumber { get; set; }
        public string ExpiryDate { get; set; }
    }
}

ETFOPortal/Areas/Commerce/Controllers/ShoppingCartController.cs
using System.Linq;
using System.ServiceModel;
using System.Web.Mvc;
using Adxstudio.Xrm.Commerce;
using Adxstudio.Xrm.Web.Mvc;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata;

namespace Site.Areas.Commerce.Controllers
{
	public class ShoppingCartController : Controller
	{
		[NoCache]
		public ActionResult Status()
		{
			var dataAdapterDependencies = new PortalConfigurationDataAdapterDependencies(requestContext: Request.RequestContext);

			// Check for existence of shopping cart schema, and return empty cart if not found.
			try
			{
				using (var serviceContext = dataAdapterDependencies.GetServiceContext())
				{
					serviceContext.Execute(new RetrieveEntityRequest
					{
						LogicalName = "adx_shoppingcart",
						EntityFilters = EntityFilters.Entity
					});
				}
			}
			catch (FaultException<OrganizationServiceFault>)
			{
				return ShoppingCart(0);
			}
			
			var dataAdapter = new ShoppingCartDataAdapter(dataAdapterDependencies, HttpContext.Profile.UserName);

			var cart = dataAdapter.SelectCart();

			if (cart == null)
			{
				return ShoppingCart(0);
			}

			var cartItems = cart.GetCartItems().ToArray();

			return ShoppingCart(cartItems.Sum(item => item.Quantity));
		}

		public JsonResult ShoppingCart(decimal count)
		{
			return Json(new ShoppingCartStatus { Count = count }, JsonRequestBehavior.AllowGet);
		}

		public class ShoppingCartStatus
		{
			public decimal Count { get; set; }
		}
	}
}

ETFOPortal/Areas/Payment/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Adxstudio.Xrm.Web.Mvc;
using Microsoft.Xrm.Portal.Configuration;
using Microsoft.Xrm.Portal.Web;
using Newtonsoft.Json.Linq;
using Site.Library;
using Site.Areas.Payment.Library;
using Site.Helpers;
using Xrm;
using log4net;
using Microsoft.Xrm.Client;
using Microsoft.Xrm.Client.Configuration;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Site.Areas.Payment.Models;
using Site.Areas.ETFO.Library;
using iTextSharp.text.pdf;
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using System.IO;
using iTextSharp.tool.xml;
using System.Xml.Linq;
using System.Threading;

namespace Site.Areas.Payment.Controllers
{
    [PortalView]
    [AjaxAuthorizeAttribute]
    public class PaymentController : BaseController, IReceiptProcessor
    {
        private static readonly ILog Log = LogManager.GetLogger(typeof(PaymentController));
        private enum EventRegistrationResult
        {
            Default = 0,
            OverlappingRegistrationCourses = 1,
            OverlappingShoppingCartCourses = 2,
            WaitingListFull = 3,
            WaitingListOffer = 4,
            SucessPayment = 5
        }

        string IReceiptProcessor.CreateReceipt(ShoppingCart model)
        {
            return this.RenderPartialViewToString("PaymentReceipt", model);
        }

        [HttpPost]
        public JsonResult ResetBackUrl()
        {
            Session["BackUrl"] = null;
            return Json(new { Success = true });
        }

        [HttpPost]
        public JsonResult AcceptWaitingListOffer(Guid eventRegistrationId, Guid eventId)
        {
            var context = XrmHelper.GetContext();
            var request = new Entity { LogicalName = "oems_waitinglistrequest" };
            request.SetAttributeValue("oems_event", new EntityReference("oems_event", eventId));
            request.SetAttributeValue("oems_eventregistration", new EntityReference("oems_eventregistration", eventRegistrationId));
            var id = context.Create(request);

            return Json(new { Success = true });
        }

        [HttpPost]
        public JsonResult UpdateEventRegistrationWithPayment(Guid eventRegistrationId, Guid eventId, string updateEventRegistrationData, string documents, string attachments, bool? returningPresenter, bool isSubmit)
        {
            try
            {
                var context = XrmHelper.GetContext();
                var result = EventRegistrationResult.Default;
                List<EventListing> overlappingRegistrationCourses = null;
                List<EventListing> overlappingShoppingCartCourses = null;
                BillingService.PaymentInfo info = null;


                Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): Start");
                var user = this.GetContact();
                var eventColumnSet = new ColumnSet(new String[] 
                {
                    "oems_waitinglistcomponentflag", "oems_eventfullflag", "oems_eventname", "oems_billingpaylater", "oems_startdate",
                    "oems_enddate", "oems_courseflag", "oems_courseterm", "oems_courseflag", "oems_coursecode", "oems_coursedateslot"
                });
                var oemsEvent = (oems_Event)context.Retrieve("oems_event", eventId, eventColumnSet);
                Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): Event: " + oemsEvent.oems_EventName + " / Contact: " + user.FullName);

                #region Save

                var eventRegistration = new oems_EventRegistration
                {
                    oems_EventRegistrationId = eventRegistrationId,
                    oems_dynamicregformdata = updateEventRegistrationData
                };

                //Returning Presenter
                if (returningPresenter.HasValue)
                {
                    Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): Returning presenter: " + returningPresenter.Value.ToString());
                    eventRegistration["oems_returningpresenter"] = returningPresenter.Value;
                }

                //Saves the event registration
                try
                {
                    if (!context.IsAttached(eventRegistration))
                    {
                        Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): Attaching event registration");
                        context.Attach(eventRegistration);
                    }

                    Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): Before saving regisration");

                    context.UpdateObject(eventRegistration);
                    context.SaveChanges();

                    Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): Registration saved");
                }
                catch (Exception ex)
                {
                    Log.Error("Error saving the registration (" + eventRegistrationId.ToString() + "): " + ex.Message);
                    if (ex.InnerException != null)
                    {
                        Log.Error("Error saving the registration (Inner Ex Message): " + ex.InnerException.Message);
                    }

                    if (ex.InnerException != null)
                    {
                        return Json(new { Success = false, Message = ex.InnerException.Message });
                    }
                    else
                    {
                        return Json(new { Success = false, Message = ex.Message });
                    }
                }

                #endregion

                #region Submit

                //Registration type
                var ercs = new ColumnSet(new String[] { "oems_registrationtype" });
                var er = (oems_EventRegistration)context.Retrieve("oems_eventregistration", eventRegistrationId, ercs);
                var registrationType = er.GetAttributeValue<OptionSetValue>("oems_registrationtype") != null ? er.GetAttributeValue<OptionSetValue>("oems_registrationtype").Value : RegistrationHelper.EventRegistrationType.Attendee;
                if (isSubmit)
                {
                    Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): Check overlapping");

                    #region Check overlapping
                    var isCourse = oemsEvent.GetAttributeValue<bool>("oems_courseflag");
                    var startDate = oemsEvent.GetAttributeValue<DateTime>("oems_startdate");
                    var endDate = oemsEvent.GetAttributeValue<DateTime>("oems_enddate");
                    if (isCourse)
                    {
                        Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): Is Course");

                        var courseDates = (from cd in context.CreateQuery("oems_coursedateslots")
                                           where cd.GetAttributeValue<Guid>("oems_coursedateslotsid") == oemsEvent.GetAttributeValue<EntityReference>("oems_coursedateslot").Id
                                           select cd).FirstOrDefault();

                        startDate = courseDates.GetAttributeValue<DateTime>("oems_startdate");
                        endDate = courseDates.GetAttributeValue<DateTime>("oems_enddate");
                        var termId = oemsEvent.GetAttributeValue<EntityReference>("oems_courseterm").Id;

                        overlappingRegistrationCourses = this.OverlapingRegistrationCourses(eventId, eventRegistrationId, termId, startDate, endDate);
                        if (overlappingRegistrationCourses.Count > 0)
                        {
                            result = EventRegistrationResult.OverlappingRegistrationCourses;
                            goto Finish;
                        }

                        overlappingShoppingCartCourses = this.OverlapingShoppingCartCourses(termId, startDate, endDate);
                        if (overlappingShoppingCartCourses.Count > 0)
                        {
                            result = EventRegistrationResult.OverlappingShoppingCartCourses;
                            goto Finish;
                        }
                    }
                    #endregion

                    Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): Check WL");

                    #region Waiting list flags
                    // + We dont offer waiting list spots to presenters
                    var waitingListComponentFlag = oemsEvent.GetAttributeValue<bool>("oems_waitinglistcomponentflag");
                    if (waitingListComponentFlag && registrationType == RegistrationHelper.EventRegistrationType.Attendee)
                    {
                        Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): WL Attendee");

                        //Registration has waiting list request in status Offered
                        var request = RegistrationHelper.GetRegistrationWithWaitingListRequest(eventId, eventRegistrationId, context);
                        if (request != null && request.GetAttributeValue<OptionSetValue>("statuscode").Value == RegistrationHelper.WaitingListStatus.Offered)
                        {
                            Log.Info("Saving Registration (" + eventRegistrationId.ToString() + "): WL offered");

                            request.SetAttributeValue("oems_accepteddate", DateTime.UtcNow);
                            if (!context.IsAttached(eventRegistration))
                            {
                                context.Attach(eventRegistration);
                            }
                            context.UpdateObject(eventRegistration);
                            context.SaveChanges();

ETFOPortal/Areas/Payment/Views/Payment/Approved.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html
@model Site.Areas.Payment.Models.ShoppingCart
@{
    var url = Url.Action("GetReceiptPDF", "Payment", new { });
    var subtitle = Html.SnippetLiteral("CreditcardProcessed/SubTitle", "Below you will find your payment details. Please <a class=\"print-pdf\" href='{0}' target=\"_blank\">print</a> this page and keep it as your transaction receipt");
    subtitle = string.Format(subtitle, url);
}

<p>
    @(Html.Raw(subtitle))
</p>

<div class="payment">
    @Html.Partial("_TransactionDetails")

    @Html.Partial("_PaymentDetails", Model)
</div>

<script>
    $(window).unload(function ()
    {
        var url = '@(Url.Action("CleanShoppingCart", "Payment", new { }))';
        $.ajax({
            type: "POST",
            url: url,
            contentType: "application/json",
            dataType: "json",
            success: function (result)
            {

            },
            error: function (xhr, ajaxOptions, thrownError)
            {
                etfo.info('Creditcard Payment', 'Something went wrong. Please try again or contact support.', null, null, null);
            }
        });
    });

    function goBack()
    {
        window.location.href = '@ViewBag.BackUrl';
    }
</script>

ETFOPortal/Areas/Payment/Views/Payment/Declined.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html
@model dynamic

<h4>ETFO – Payment Declined</h4>

<p>@(Html.Raw(Html.SnippetLiteral("Payment_Declined", "The payment has been declined, please contact us if you continue to experience problems.")))</p>
@if (ViewBag.RegistrationId != null)
{
    <p><a href="@(Url.Action("PayNow", "Payment", new { registrationId = ViewBag.RegistrationId }))">Click here</a> if you want to try your payment again.</p>
}

ETFOPortal/Areas/Payment/Views/Payment/Failed.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html
@model dynamic

<h4>ETFO – Payment Failed</h4>

<p>@(Html.Raw(Html.SnippetLiteral("Payment_Failed", "Payment failed because the timeout has been exceeded.")))</p>
@if (ViewBag.RegistrationUrl != null)
{
    <p><a href="@(Url.Action("ShoppingCart", "Payment"))">Click here</a> to try again.</p>
}

ETFOPortal/Areas/Payment/Views/Payment/PayLater.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html
@model Site.Areas.Payment.Models.ShoppingCart
@{
    var url = Url.Action("GetReceiptPDF", "Payment", new { });
    var subtitle = Html.SnippetLiteral("PayLater/SubTitle", "Below you will find your payment details. Please <a class=\"print-pdf\" href='{0}' target=\"_blank\">print</a> a copy of this:");
    subtitle = string.Format(subtitle, url);
}

<p>
    @(Html.Raw(Html.SnippetLiteral("PayLater/Title", "Pay Later Confirmation")))
</p>
<p>
    @(Html.Raw(subtitle))
</p>

<div class="payment">
    @Html.Partial("_PaymentDetails", Model)
</div>

<br />
<p>
    <input id="btnBack" type="button" onclick='goBack();' class="btn btn-primary  pull-right" value="@Html.SnippetLiteral("Payment/GoBack", "Back")">
</p>


<script>
    $(window).unload(function ()
    {
        var url = '@(Url.Action("CleanShoppingCart", "Payment", new { }))';
        $.ajax({
            type: "POST",
            url: url,
            contentType: "application/json",
            dataType: "json",
            success: function (result)
            {
                
            },
            error: function (xhr, ajaxOptions, thrownError)
            {
                etfo.info('PayCheque', 'Something went wrong. Please try again or contact support.', null, null, null);
            }
        });
    });

    function goBack()
    {
        window.location.href = '@ViewBag.BackUrl';
    }
</script>

ETFOPortal/Areas/Payment/Views/Payment/PayLocal.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html
@model Site.Areas.Payment.Models.ShoppingCart
@{
    var url = Url.Action("GetReceiptPDF", "Payment", new { });
    var localName = Model.Details.ElementAt(0).Value.PaymentInfo.LocalName;
    //var subtitle = Html.SnippetLiteral("PayLocal/SubTitle", "Below you will find your payment details for local <b>{0}</b>. Please <a class=\"print-pdf\" href='{1}' target=\"_blank\">print</a> a copy of this:");
    var subtitle = Html.SnippetLiteral("PayLocal/SubTitle", "Below you will find your payment details for local <b>{0}</b>.");
    subtitle = string.Format(subtitle, localName, url);
}

<p>
    @(Html.Raw(Html.SnippetLiteral("PayLocal/Title", "Charge To Local Confirmation")))
</p>
<p>
    @(Html.Raw(subtitle))
</p>

<div class="payment">
    @Html.Partial("_PaymentDetails", Model)
</div>

<br />
<p>
    <input id="btnBack" type="button" onclick='goBack();' class="btn btn-primary  pull-right" value="@Html.SnippetLiteral("Payment/GoBack", "Back")">
</p>


<script>
    $(window).unload(function ()
    {
        var url = '@(Url.Action("CleanShoppingCart", "Payment", new { }))';
        $.ajax({
            type: "POST",
            url: url,
            contentType: "application/json",
            dataType: "json",
            success: function (result)
            {
                
            },
            error: function (xhr, ajaxOptions, thrownError)
            {
                etfo.info('PayCheque', 'Something went wrong. Please try again or contact support.', null, null, null);
            }
        });
    });

    function goBack()
    {
        window.location.href = '@ViewBag.BackUrl';
    }
</script>

ETFOPortal/Areas/Payment/Views/Payment/PayNow.cshtml
@using Site.Areas.Payment.Library
@model BillingService.PaymentPreloadInfo
@{
    var url = BillingService.MonerisBaseUrl + BillingService.MonerisTransactionPath;
}

<div id="moneris-data-container">
    <form id="monerisForm" method="POST" action="@(url)">
        <input type="hidden" name="hpp_id" value="@(Model.HppId)" />
        <input type="hidden" name="hpp_preload" value="" />
        <input type="hidden" name="ticket" value="@(Model.Ticket)" />

        @*<INPUT TYPE="SUBMIT" NAME="SUBMIT" VALUE="SUBMIT" />*@
    </form>
</div>

<script type="text/javascript">
    $(function ()
    {
        $("#monerisForm").submit();
    });
</script>

ETFOPortal/Areas/Payment/Views/Payment/Payed.cshtml
@model Site.Areas.Payment.Models.ShoppingCart

<p>Here you find your payment details:</p>

<div class="payment">
    @Html.Partial("_PaymentDetails", Model)
</div>

ETFOPortal/Areas/Payment/Views/Payment/PaymentReceiptPDF.cshtml
@model Site.Areas.Payment.Models.ShoppingCart
@{
    Layout = null;
}

<html>
	<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <title></title>
	</head>    <body style="font-family:Open Sans,Helvetica,Arial,sans-serif;color: #333333">
        <div id="content-container" class="container">
		    <div id="content">
	            <div class="row etfo-row-wrap">
		            <div class="span9 etfo-main-wrap">
		                <div class="page-heading">
                            <div class="page-header" style="padding-bottom: 9px; margin: 20px 0 30px; border-bottom: 1px solid #eeeeee;">        
                                <h1 style="font-size: 38px; line-height: 40px; color: #01305E; font-weight: normal; margin: 10px 0">
                                    ETFO – Payment Receipt
                                </h1>
	                        </div>
	                    </div>
                        @*<p style="font-size: 14px; line-height: 20px; margin-top: 20px">PDF Receipt Test</p>*@
                        <div id="receipt-container" class="payment">
                            @if (Model.CreditCard != null)
                            {
                                <div style="font-size: 14px; line-height: 20px; background-color: #2980b9; color: #fff;font-weight: bold;padding: 4px;margin: 20px 0; width:100%">Transaction Details</div>
                                <table>
                                    <tr>
                                        <td style="padding-bottom: 10px;">&nbsp;</td>
                                        <td style="padding-bottom: 10px;">&nbsp;</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Transaction ID:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.TransactionID</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Transaction Type:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.TransactionType</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Date and Time:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.DateandTime</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Payment Amount:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.PaymentAmount</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Authorization Code:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.AuthorizationCode</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Response Code:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.ResponseCode</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>ISO Code:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.ISOCode</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Message:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.Message</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Reference Number:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.ReferenceNumber</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Name on the Card</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.NameOnTheCard</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Credit Card Number:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.CreditCardNumber</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;"><b>Expiry Date:</b></td>
                                        <td style="padding-bottom: 10px;">@Model.CreditCard.ExpiryDate</td>
                                    </tr>
                                    <tr>
                                        <td style="padding-bottom: 10px;">&nbsp;</td>
                                        <td style="padding-bottom: 10px;">&nbsp;</td>
                                    </tr>
                                </table>
                            }

                            @Html.Partial("_PaymentDetailsPDF", Model)
                        </div>
		            </div>
                </div>
			</div>
		</div>
    </body></html>

ETFOPortal/Areas/Payment/Views/Payment/ProcessedTest.cshtml
@model Site.Areas.Payment.Models.ShoppingCart

<p>Please print this page and keep it as your transaction receipt</p>

<div id="receipt-container" class="payment">
    @Html.Partial("_TransactionDetails")

    @Html.Partial("_PaymentDetails", Model)

@*    <a href="javascript:void(0);" class="k-button k-button-icontext k-grid-pdf export-pdf">
        <span class="k-icon k-i-pdf"></span>
        Export Pdf
    </a>*@
</div>

@*<!-- Operation js -->
<script src="~/js/kendo/2017.1.223/kendo.web.min.js"></script>
<!-- Load Pako ZLIB library to enable PDF compression -->
<script src="~/js/pako_deflate.min.js"></script>
<!-- Form js -->
<script src="~/Areas/MyReports/js/coursesreceipt.js"></script>*@

ETFOPortal/Areas/Payment/Views/Payment/ZeroPayment.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html
@model Site.Areas.Payment.Models.ShoppingCart

@if (ViewBag.IsDeferralPayment)
{
    <p>
        @(Html.Raw(Html.SnippetLiteral("ShoppingCart/DeferralPayment", "The events have been payed with your deferral. Your new deferral amount is: $")))@(ViewBag.NewDeferral.ToString("F"))
    </p>
    <p>
        Below you will find your payment details. Please print a copy of this.
    </p>
}
else
{
    <p>
        @(Html.Raw(Html.SnippetLiteral("ShoppingCart/ZeroPayment", "The events have no payment")))
    </p>
    <p>
        Below you will find your details. Please print a copy of this.
    </p>
}        

<div class="payment">
    @Html.Partial("_PaymentDetails", Model)
</div>

ETFOPortal/Areas/Payment/Views/Payment/_TransactionDetails.cshtml
@using Site.Areas.Payment.Library
@{ 
    var expireDate = Request.Form[BillingService.MonerisResponse.ExpiryDate];
    var month = expireDate.Substring(2, 2);
    var year = expireDate.Substring(0, 2);

    var expiryFormatedDate = month + year;
}

<div class="receipt-title">Transaction Details</div>
    <table>
        <tr>
            <td><b>Transaction ID:</b></td>
            <td>@Request.Form[BillingService.MonerisResponse.ResponseOrderId]</td>
        </tr>
        <tr>
            <td><b>Transaction Type:</b></td>
            <td>@Request.Form[BillingService.MonerisResponse.TransName]</td>
        </tr>
        <tr>
            <td><b>Date and Time:</b></td>
            <td>@Request.Form[BillingService.MonerisResponse.DateStamp] @Request.Form[BillingService.MonerisResponse.TimeStamp]</td>
        </tr>
        <tr>
            <td><b>Payment Amount:</b></td>
            <td>@Request.Form[BillingService.MonerisResponse.ChargeTotal]</td>
        </tr>
        <tr>
            <td><b>Authorization Code:</b></td>
            <td>@Request.Form[BillingService.MonerisResponse.BankApprovalCode]</td>
        </tr>
        <tr>
            <td><b>Response Code:</b></td>
            <td>@Request.Form[BillingService.MonerisResponse.ResponseCode]</td>
        </tr>
        <tr>
            <td><b>ISO Code:</b></td>
            <td>@Request.Form[BillingService.MonerisResponse.IsoCode]</td>
        </tr>
        <tr>
            <td><b>Message:</b></td>
            <td>@Request.Form[BillingService.MonerisResponse.Message]</td>
        </tr>
        <tr>
            <td><b>Reference Number:</b></td>
            <td>@Request.Form[BillingService.MonerisResponse.BankTransactionId]</td>
        </tr>
        <tr>
            <td><b>Name on the Card</b></td>
            <td>@Request.Form[BillingService.MonerisResponse.Cardholder]</td>
        </tr>
        <tr>
            <td><b>Credit Card Number:</b></td>
            @if (Model.IsAsyncRequest)
            {
                <td>@Request.Form[BillingService.MonerisResponse.CardNumberAsync]</td>
            }
            else
            {
                <td>@Request.Form[BillingService.MonerisResponse.CardNumber]</td>
            }
        </tr>
        <tr>
            <td><b>Expiry Date:</b></td>
            <td>@expiryFormatedDate</td>
        </tr>
    </table>