ETFOPortal/Areas/Marketing/Controllers/MarketingController.cs
using System;
using System.Collections.Generic;
using System.Threading;
using System.Web.Mvc;
using Adxstudio.Xrm.Marketing;
using Adxstudio.Xrm.Web.Mvc;
using Adxstudio.Xrm.Web.Mvc.Html;
using Microsoft.Xrm.Portal.Configuration;

namespace Site.Areas.Marketing.Controllers
{
	public class MarketingController : Controller
	{
		private readonly Lazy<IMarketingDataAdapter> _dataAdapter = new Lazy<IMarketingDataAdapter>(GetMarketingDataAdapter, LazyThreadSafetyMode.None);

		private IMarketingDataAdapter DataAdapter
		{
			get { return _dataAdapter.Value; }
		}

		[HttpGet]
		public ActionResult ManageSubscriptions(string encodedEmail, string signature)
		{
			var marketingLists = DataAdapter.GetMarketingLists(encodedEmail, signature);

			return ToRazor("ManageSubscriptions", marketingLists, "Manage Subscriptions");
		}

		[HttpPost]
		public ActionResult ManageSubscriptions(string encodedEmail, string signature, FormCollection form)
		{
			IEnumerable<IMarketingList> unsubscribedLists;
			if (form.GetValue("fromList") != null)
			{
				var listsValue = form.GetValue("lists");
				if (listsValue != null)
				{
					var lists = listsValue.AttemptedValue.Split(',');
					unsubscribedLists = DataAdapter.Unsubscribe(encodedEmail, lists, signature);
				}
				else
				{
					unsubscribedLists = new List<IMarketingList>();
				}
			}
			else
			{
				unsubscribedLists = DataAdapter.Unsubscribe(encodedEmail, signature);
			}

			AddLinkRoute(encodedEmail, signature);
			return ToRazor("Success", unsubscribedLists, "Unsubscription Success");
		}

		[HttpGet]
		public ActionResult Unsubscribe(string encodedEmail, string encodedList, string signature)
		{
			var unsubscribedLists = DataAdapter.Unsubscribe(encodedEmail, encodedList, signature);
			var newSignature = DataAdapter.ConstructSignature(encodedEmail);
			AddLinkRoute(encodedEmail, newSignature);
			return ToRazor("Success", unsubscribedLists, "Unsubscription Success");
		}

		private void AddLinkRoute(string encodedEmail, string signature)
		{
			ViewData["LinkRoute"] = new
			{
				encodedEmail,
				signature
			};
		}

		private PortalViewContext PortalViewContext()
		{
			var dataAdapterDependencies = new PortalConfigurationDataAdapterDependencies(requestContext: Request.RequestContext);
			var portalViewContext = new PortalViewContext(dataAdapterDependencies, requestContext: Request.RequestContext);
			return portalViewContext;
		}

		private ViewResult ToRazor(string viewName, object model, string title)
		{
			ViewData.Model = model;
			ViewBag.Title = title;
			ViewBag._ViewName = viewName;
			
			ViewData[PortalExtensions.PortalViewContextKey] = PortalViewContext();

			return new ViewResult
			{
				ViewName = "_RazorLayout",
				ViewData = ViewData
			};
		}
		
		private static IMarketingDataAdapter GetMarketingDataAdapter()
		{
			var portalContext = PortalCrmConfigurationManager.CreatePortalContext();
			var dependencies = new PortalContextDataAdapterDependencies(portalContext);
			return new MarketingDataAdapter(dependencies);
		}
	}
}

ETFOPortal/Areas/Marketing/Views/Marketing/ManageSubscriptions.cshtml
@model IEnumerable<Adxstudio.Xrm.Marketing.IMarketingList>
@using Adxstudio.Xrm.Web.Mvc.Html

@{
	Layout = "~/Areas/Marketing/Views/Shared/_Layout.cshtml";
}

@if (Model.Any())
{
	<p>@Html.Raw(Html.SnippetLiteral("Unsubscribe/Manage/InstructionMessage", "Please select the marketing lists from which you wish to <strong>unsubscribe</strong>."))</p>
	<form method="POST">
		<table class="table table-responsive table-hover list-unsubscribe">
			<thead>
				<tr>
					<th><span class='sr-only'>Select List</span></th>
					<th>List</th>
					<th>Purpose</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var list in Model)
				{
					<tr>
						<td class="input-label"><label><input type="checkbox" name="lists" id="list_{@list.Id.ToString("N")}" value="@list.Id.ToString("D")" aria-labelledby="list_{@list.Id.ToString("N")}_List list_{@list.Id.ToString("N")}_Purpose" /></label></td>
						<td class="input-label"><label id="list_{@list.Id.ToString("N")}_List" for="list_{@list.Id.ToString("N")}">@list.Name</label></td>
						<td class="input-label"><label id="list_{@list.Id.ToString("N")}_Purpose" for="list_{@list.Id.ToString("N")}">@Html.Raw(string.IsNullOrEmpty(list.Purpose) ? "&nbsp;" : list.Purpose)</label></td>
					</tr>
				}
			</tbody>
		</table>
		<button type="submit" class="btn btn-primary" name="fromList">@Html.Raw(Html.SnippetLiteral("UnsubscribeButtonText", "Unsubscribe"))</button>
		<button type="submit" class="btn btn-info" name="all">@Html.Raw(Html.SnippetLiteral("UnsubscribeAllButtonText", "Unsubscribe All"))</button>
	</form>
}
else
{
	<p class="alert alert-warning">@Html.Raw(Html.SnippetLiteral("Unsubscribe/Manage/NoListsMessage", "There are no marketing lists."))</p>
}

ETFOPortal/Areas/Marketing/Views/Marketing/Success.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html
@model IEnumerable<Adxstudio.Xrm.Marketing.IMarketingList>

@{
	Layout = "~/Areas/Marketing/Views/Shared/_Layout.cshtml";
}

@if (Model.Any())
{
	<p class="alert alert-success">@Html.Raw(Html.SnippetLiteral("Unsubscribe/Success/SuccessMessage", "You have been successfully removed from the following list(s):"))</p>
	<table class="table table-responsive table-striped">
		<thead>
			<tr>
				<th><span class="sr-only">Success</span></th>
				<th>List</th>
				<th>Purpose</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var list in Model)
			{
				<tr>
					<td><span class="fa fa-check-circle"></span></td>
					<td>@list.Name</td>
					<td>@list.Purpose</td>
				</tr>
			}
		</tbody>
	</table>
}
else
{
	<p class="alert alert-warning">@Html.Raw(Html.SnippetLiteral("Unsubscribe/Success/RemovedFromNoneMessage", "You have not been removed from any lists."))</p>
}
<p>
	<a href="@Url.Action("ManageSubscriptions", "Marketing", ViewData["LinkRoute"])">@Html.Raw(Html.SnippetLiteral("Unsubscribe/Success/ManageSubscriptionLinkMessage", "Manage More Subscriptions..."))</a>
</p>