ETFOPortal/Areas/MyReports/Models/AttendeeDetailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.Xrm;
using Microsoft.Xrm.Client;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Site.Helpers;
using Xrm;

namespace Site.Areas.MyReports.Models
{
    public class AttendeeDetailModel
    {
        public int? Number { get; set; }
        public string Name { get; set; }
        public string OrderName { get; set; }
        public string SchoolBoard { get; set; }
        public List<string> AttendanceDatesList { get; set; }
        public string AttendanceDates { get; set; }
    }
}

ETFOPortal/Areas/MyReports/Models/AttendeeModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.Xrm;
using Microsoft.Xrm.Client;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Site.Helpers;
using Xrm;

namespace Site.Areas.MyReports.Models
{
    public class AttendeeModel
    {
        public int? Number { get; set; }
        public Guid UserId { get; set; }
        public string Name { get; set; }
        public string OrderName { get; set; }
        public string Mail { get; set; }        
        public string SchoolBoard { get; set; }
        public string NumberOfYearsTeaching { get; set; }
        public string CurrentAssignment { get; set; }
        public string FutureTeachingAssignment { get; set; }
    }
}

ETFOPortal/Areas/MyReports/Models/BasicModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.Xrm;
using Microsoft.Xrm.Client;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Site.Helpers;
using Xrm;

namespace Site.Areas.MyReports.Models
{
    /// <summary>
    /// My Reports Basic Model
    /// </summary>
    public class BasicModel
    {
        public int? EventStatus { get; set; }
        public string EventStatusText { get; set; }
        public Guid? EventCategoryId { get; set; }
        public string EventCategoryName { get; set; }
        public Guid? EventSubCategoryId { get; set; } 
        public string EventSubCategoryName { get; set; }
        public Guid? EventId { get; set; }
        public string EventTitle { get; set; }
        public string EventDescription { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public Guid? RegistrationId { get; set; }
        public int? RegistrationStatus { get; set; }
        public string RegistrationStatusText { get; set; }
        public DateTime? RegistrationStartDate { get; set; }
        public DateTime? RegistrationEndDate { get; set; }
        public Guid? CourseTermId { get; set; }
    }

    /// <summary>
    /// General report filter
    /// </summary>
    public class BasicFilter
    {
        //Event Listing
        public int? Status;
        public Guid? CategoryId;
        public Guid? SubCategoryId;
        public string EventName;
        public DateTime? EventStartDate;
        public DateTime? EventEndDate;
        public int? EventRegistrationStatusId;
        public DateTime? EventRegistrationStartDate;
        public DateTime? EventRegistrationEndDate;
    }

}

ETFOPortal/Areas/MyReports/Models/CourseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.Areas.MyReports.Models
{
    /// <summary>
    /// Release Time Request report
    /// </summary>
    public class CourseModel : BasicModel
    {
        public string CourseCode { get; set; }
        public string Topic { get; set; }
        public DateTime? InitialOferedDate { get; set; }
        public DateTime? FinalOferedDate { get; set; }
        public string InitialDailyTime { get; set; }
        public string FinalDailyTime { get; set; }
    }
}

ETFOPortal/Areas/MyReports/Models/EventListingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.Areas.MyReports.Models
{
    /// <summary>
    /// Event Listing report
    /// </summary>
    public class EventListingModel : BasicModel
    {
        public string CourseTermCode { get; set; }
        public string CourseTermName { get; set; }
        public int? RegistrationCaucusStatus { get; set; }
        public string RegistrationCaucusStatusText { get; set; }
        public int? RegistrationChildCareStatus { get; set; }
        public string RegistrationChildCareStatusText { get; set; }
        public int? RegistrationAccommodationStatus { get; set; }
        public string RegistrationAccommodationStatusText { get; set; }
        public int? RegistrationReleaseStatus { get; set; }
        public string RegistrationReleaseStatusText { get; set; }
        public int? ApplicationWorkshopStatus { get; set; }
        public string ApplicationWorkshopStatusText { get; set; }
        public bool WaitingListFlag { get; set; }
        public int? BillingPaymentStatus { get; set; }
        public string BillingPaymentStatusText { get; set; }
        public int? BillingPaymentMethod { get; set; }
        public string BillingPaymentMethodText { get; set; }
        public decimal? BillingDeferral { get; set; }
        public decimal? BillingTotalToPay { get; set; }
    }
}

ETFOPortal/Areas/MyReports/Models/InstructorCourseHistoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.Areas.MyReports.Models
{
    /// <summary>
    /// Release Time Request report
    /// </summary>
    public class InstructorCourseHistoryModel : BasicModel
    {
        public string CourseTermCode { get; set; }
        public string CourseTermName { get; set; }
        public string CourseTitle { get; set; }
        public string CourseDescription { get; set; }
    }
}

ETFOPortal/Areas/MyReports/Models/InstructorCourseListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.Areas.MyReports.Models
{
    /// <summary>
    /// Release Time Request report
    /// </summary>
    public class InstructorCourseListModel : BasicModel
    {
        public string CourseTermCode { get; set; }
        public string CourseTermName { get; set; }
        public string CourseTitle { get; set; }
        public string CourseCode { get; set; }
        public string CourseDates { get; set; }
        public string CourseTimes { get; set; }
        public string CourseLocation { get; set; }
    }
}

ETFOPortal/Areas/MyReports/Models/LocalDelegationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.Areas.MyReports.Models
{
    /// <summary>
    /// Local Delegation reports filter
    /// </summary>
    public class LocalDelegationReportsFilters : BasicFilter
    {
        public int? LocalDelegationStatus;
    }

    /// <summary>
    /// Release Time Request report
    /// </summary>
    public class LocalDelegationModel : BasicModel
    {
        public Guid? LocalDelegationId { get; set; }
        public string LocalDelegationName { get; set; }
        public int? LocalDelegationStatus { get; set; }
        public string LocalDelegationStatusText { get; set; }
    }
}

ETFOPortal/Areas/MyReports/Controllers/MyReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Adxstudio.Xrm.Web.Mvc;
using Microsoft.Xrm.Portal.Configuration;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata;
using Org.BouncyCastle.Crypto.Engines;
using Site.Helpers;
using Site.Library;
using Xrm;
using Site.Areas.MyReports.Library;
using Site.Areas.MyReports.Models;
using Microsoft.Xrm.Sdk.Query;
using Newtonsoft.Json;
using System.Globalization;

namespace Site.Areas.MyReports.Controllers
{
    [PortalView]
    [Authorize]
    public class MyReportsController : Controller
    {
        #region Event Listing

        /// <summary>
        /// Event listing report main view
        /// </summary>
        public ActionResult EventListing()
        {
            ViewBag.Title = XrmHelper.GetSnippetValueOrDefault("MyReports/EventListing/PageTitle", "Event Listing");
            ViewBag.Description = XrmHelper.GetSnippetValueOrDefault("MyReports/EventListing/Description", "Search for all Events with a Registration Form associated with this user that match the above criteria");
            ViewBag.Breadcrumb = XrmHelper.GetSnippetValueOrDefault("MyReports/EventListing/Breadcrumb", "My Reports");
            ViewBag.PresidentFlag = this.IsPresident();

            return this.RazorView();
        }

        /// <summary>
        /// Gets the event listing report data
        /// </summary>
        [HttpPost]
        public JsonResult GetEventListings(FormCollection formValues)
        {
            var portal = PortalCrmConfigurationManager.CreatePortalContext();

            // Filters
            BasicFilter filters = this.LoadFilters(formValues);
            MyReportsListing reportsListing = new MyReportsListing(filters, portal.User.Id);
            var results = reportsListing.EventListingGetData();

            var model = new
            {
                data = results,
                total = results.Count
            };

            return new JsonNetResult() { Data = model };
        }

        #endregion

        #region Release Time Request

        /// <summary>
        /// Release time request report main view
        /// </summary>
        /// <returns></returns>
        public ActionResult ReleaseTimeRequest()
        {
            ViewBag.Title = XrmHelper.GetSnippetValueOrDefault("MyReports/ReleaseTimeRequest/PageTitle", "Release Time Request");
            ViewBag.Description = XrmHelper.GetSnippetValueOrDefault("MyReports/ReleaseTimeRequest/Description", "Search for all Events with a Registration Form associated with this user with a Release Time Request that match the above criteria");
            ViewBag.Breadcrumb = XrmHelper.GetSnippetValueOrDefault("MyReports/ReleaseTimeRequest/Breadcrumb", "My Reports");
            ViewBag.PresidentFlag = this.IsPresident();

            return this.RazorView();
        }

        /// <summary>
        /// Gets the release time request report data
        /// </summary>
        [HttpPost]
        public JsonResult GetReleaseTimeRequest(FormCollection formValues)
        {
            var portal = PortalCrmConfigurationManager.CreatePortalContext();

            // Filters
            BasicFilter filters = this.LoadFilters(formValues);
            var serializedFilters = JsonConvert.SerializeObject(filters);
            MyReleaseTimeReportsFilters releaseFilter = JsonConvert.DeserializeObject<MyReleaseTimeReportsFilters>(serializedFilters);
            int releaseTimeRequestStatus = Convert.ToInt32(formValues["releaseTimeRequestStatus"]);
            releaseFilter.ReleaseTimeRequestStatus = releaseTimeRequestStatus == -1 ? (int?)null : releaseTimeRequestStatus;

            MyReportsListing reportsListing = new MyReportsListing(releaseFilter, portal.User.Id);
            var results = reportsListing.ReleaseTimeRequestGetData();

            var model = new
            {
                data = results,
                total = results.Count
            };

            return new JsonNetResult() { Data = model };
        }

        /// <summary>
        /// Loads the status filters
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult LoadReleaseTimeStatusFilters()
        {
            var context = XrmHelper.GetContext();

            //releast time request status
            RetrieveAttributeRequest attributeRequest = new RetrieveAttributeRequest
            {
                EntityLogicalName = "oems_releasetimerequest",
                LogicalName = "statuscode"
            };
            var releases = PopulateStatusDropdownList(context, attributeRequest);

            var result = new { Releases = releases };
            return Json(result);
        }

        #endregion

        #region Local Delegation

        /// <summary>
        /// Local delegation report main view
        /// </summary>
        /// <returns></returns>
        public ActionResult LocalDelegation()
        {
            ViewBag.PresidentFlag = this.IsPresident();
            if (!ViewBag.PresidentFlag)
                this.RazorView("EventListing");

            ViewBag.Title = XrmHelper.GetSnippetValueOrDefault("MyReports/Local Delegation/PageTitle", "Local Delegation");
            ViewBag.Description = XrmHelper.GetSnippetValueOrDefault("MyReports/Local Delegation/Description", "Search for all Events with a Local Delegation associated with this user (i.e. that match the user’s Local Office) that match the above criteria.");
            ViewBag.Breadcrumb = XrmHelper.GetSnippetValueOrDefault("MyReports/Local Delegation/Breadcrumb", "My Reports");

            return this.RazorView();
        }

        /// <summary>
        /// Gets the release time request report data
        /// </summary>
        [HttpPost]
        public JsonResult GetLocalDelegation(FormCollection formValues)
        {
            var portal = PortalCrmConfigurationManager.CreatePortalContext();

            // Filters
            BasicFilter filters = this.LoadFilters(formValues);
            var serializedFilters = JsonConvert.SerializeObject(filters);
            LocalDelegationReportsFilters localDelegationFilter = JsonConvert.DeserializeObject<LocalDelegationReportsFilters>(serializedFilters);
            int localDelegationStatus = Convert.ToInt32(formValues["localDelegationStatus"]);
            localDelegationFilter.LocalDelegationStatus = localDelegationStatus == -1 ? (int?)null : localDelegationStatus;

            MyReportsListing reportsListing = new MyReportsListing(localDelegationFilter, portal.User.Id);
            var results = reportsListing.LocalDelegationGetData();

            var model = new
            {
                data = results,
                total = results.Count
            };

            return new JsonNetResult() { Data = model };
        }

        /// <summary>
        /// Loads the status filters
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public JsonResult LoadLocalDelegationStatusFilters()
        {
            var context = XrmHelper.GetContext();

            //Local delegation status
            RetrieveAttributeRequest attributeRequest = new RetrieveAttributeRequest
            {
                EntityLogicalName = "oems_eventlocal",
                LogicalName = "statuscode"
            };
            var locals = PopulateStatusDropdownList(context, attributeRequest);

            var result = new { Locals = locals };
            return Json(result);
        }

        #endregion

        #region My Receipts

        /// <summary>
        /// My course receipt report main view
        /// </summary>
        /// <returns></returns>
        public ActionResult MyCourseReceipt()
        {
            ViewBag.Title = XrmHelper.GetSnippetValueOrDefault("MyReports/MyCourseReceipt/PageTitle", "My Course Receipts");
            ViewBag.Description = XrmHelper.GetSnippetValueOrDefault("MyReports/MyCourseReceipt/Description", "ETFO Summer Academy Receipts");
            ViewBag.Breadcrumb = XrmHelper.GetSnippetValueOrDefault("MyReports/MyCourseReceipt/Breadcrumb", "My Reports");
            ViewBag.PresidentFlag = this.IsPresident();

            var context = XrmHelper.GetContext();
            var portal = PortalCrmConfigurationManager.CreatePortalContext();
            Entity user = context.Retrieve(portal.User.LogicalName, portal.User.Id, new ColumnSet("fullname", "address1_name"));
            ViewBag.Attendee = user.GetAttributeValue<string>("fullname");
            ViewBag.Address = user.GetAttributeValue<string>("address1_name");

            return this.RazorView();
        }

        [HttpPost]
        public JsonResult GetCourseReceipt()
        {
            // Filters
            var portal = PortalCrmConfigurationManager.CreatePortalContext();
            MyReportsListing reportsListing = new MyReportsListing(null, portal.User.Id);
            var results = reportsListing.MyCourseReceiptGetData();

            var model = new
            {
                data = results,
                total = results.Count
            };

            return new JsonNetResult() { Data = model };
        }

        /// <summary>
        /// My events receipt report main view
        /// </summary>
        /// <returns></returns>
        public ActionResult MyEventsReceipt()
        {
            ViewBag.Title = XrmHelper.GetSnippetValueOrDefault("MyReports/MyEventsReceipt/PageTitle", "My Events Receipts");
            ViewBag.Description = XrmHelper.GetSnippetValueOrDefault("MyReports/MyEventsReceipt/Description", "ETFO Summer Academy Receipts");
            ViewBag.Breadcrumb = XrmHelper.GetSnippetValueOrDefault("MyReports/MyEventsReceipt/Breadcrumb", "My Reports");
            ViewBag.PresidentFlag = this.IsPresident();

            var context = XrmHelper.GetContext();

ETFOPortal/Areas/MyReports/Views/MyReports/EventListing.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html

<link rel="stylesheet" href="~/css/kendo/2017.1.223/kendo.common.min.css"/>
<link rel="stylesheet" href="~/css/kendo/2017.1.223/kendo.bootstrap.min.css" />

<!-- Menu -->
@Html.Partial("_Menu")

<div id="filter-container">
    <form role="form" method="post"  action="javascript:void(0);" id="filter-form">
        <h4 id="report-title"></h4>
        <div class="body">
            <div class="table">
                <!-- Common filter -->
                @Html.Partial("_Basicfilter")

                <!-- Search Button -->
                <br />
                <div class="row pull-right">
                    <div class="col-md-2 col-sm-2">
                        <button id="search-tg" type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
                <br /><br />
            </div> 
        </div>
    </form>
</div>
<br />
<div id="results-container">
    <h4 id="search-title"></h4>
    <br />
    <div class="row">
        <div class="tk-grid">
            <div id="my-reports-grid"></div>
        </div>
    </div>
</div>

<!-- Operation js -->
<script src="~/js/kendo/2017.1.223/kendo.web.min.js"></script>
<script src="~/js/kendo/2017.1.223/cultures/kendo.culture.en-CA.min.js"></script>
<script src="~/js/jquery.form.min.js"></script>
<!-- Used to export to excel -->
<script src="~/js/jszip.min.js"></script>
<!-- Load Pako ZLIB library to enable PDF compression -->
<script src="~/js/pako_deflate.min.js"></script>
<!-- Form js -->
<script src="~/js/ETFO/base.core.js"></script>
<script src="~/js/ETFO/ajax.update.progress.js"></script>
<script>
    // Basic filter Variables
    var urlLoadBasicStatusDropDowns = '@(Url.Action("LoadBasicStatusFilters", "MyReports", new object { }))';
    var urlLoadCategories = '@(Url.Action("LoadCategories", "MyReports", new object { }))';
    var urlLoadSubcategories = '@(Url.Action("LoadSubcategories", "MyReports", new object { }))';

    // Form Variables
    var urlSearch = '@(Url.Action("GetEventListings", "MyReports"))';
    var urlProxy = '@(Url.Action("KendoSave", "MyReports"))';
    
    $(document).ready(function ()
    {
        $("#myresults-menu").kendoMenu();
        $(".menu-eventlisting").addClass("k-state-selected")
    });
</script>
<script src="~/Areas/MyReports/js/eventlisting.js"></script>
<script src="~/Areas/MyReports/js/basicfilter.js"></script>

ETFOPortal/Areas/MyReports/Views/MyReports/InstructorCourseHistory.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html

<link rel="stylesheet" href="~/css/kendo/2017.1.223/kendo.common.min.css"/>
<link rel="stylesheet" href="~/css/kendo/2017.1.223/kendo.bootstrap.min.css" />

<!-- Menu -->
@Html.Partial("_Menu")

<div id="filter-container">
    <form role="form" method="post"  action="javascript:void(0);" id="filter-form">
        <h4 id="report-title"></h4>
        <div class="body">
            <div class="table">
                <!-- Common filter -->
                @Html.Partial("_BasicFilter")

                <!-- Search Button -->
                <br />
                <div class="row pull-right">
                    <div class="col-md-2 col-sm-2">
                        <button id="search-tg" type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
                <br /><br />
            </div> 
        </div>
    </form>
</div>
<br />
<div id="results-container">
    <h4 id="search-title"></h4>
    <br />
    <div class="row">
        <div class="tk-grid">
            <div id="my-reports-grid"></div>
        </div>
    </div>
</div>

<!-- Operation js -->
<script src="~/js/kendo/2017.1.223/kendo.web.min.js"></script>
<script src="~/js/kendo/2017.1.223/cultures/kendo.culture.en-CA.min.js"></script>
<script src="~/js/jquery.form.min.js"></script>
<!-- Used to export to excel -->
<script src="~/js/jszip.min.js"></script>
<!-- Load Pako ZLIB library to enable PDF compression -->
<script src="~/js/pako_deflate.min.js"></script>
<!-- Form js -->
<script src="~/js/ETFO/base.core.js"></script>
<script src="~/js/ETFO/ajax.update.progress.js"></script>
<script>
    // Basic filter Variables
    var urlLoadBasicStatusDropDowns = '@(Url.Action("LoadBasicStatusFilters", "MyReports", new object { }))';
    var urlLoadCategories = '@(Url.Action("LoadCategories", "MyReports", new object { }))';
    var urlLoadSubcategories = '@(Url.Action("LoadSubcategories", "MyReports", new object { }))';

    // Form Variables
    var urlSearch = '@(Url.Action("GetInstructorCourseHistory", "MyReports"))';
    var urlProxy = '@(Url.Action("KendoSave", "MyReports"))';

    $(document).ready(function ()
    {
        $("#myresults-menu").kendoMenu();
        $(".menu-instructors").addClass("k-state-selected")
        $(".menu-instructorcoursehistory").addClass("k-state-selected")
    });
</script>
<script src="~/Areas/MyReports/js/instructorCourseHistory.js"></script>
<script src="~/Areas/MyReports/js/basicfilter.js"></script>

ETFOPortal/Areas/MyReports/Views/MyReports/InstructorCourseList.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html

<link rel="stylesheet" href="~/css/kendo/2017.1.223/kendo.common.min.css"/>
<link rel="stylesheet" href="~/css/kendo/2017.1.223/kendo.bootstrap.min.css" />

<!-- Menu -->
@Html.Partial("_Menu")

<div id="filter-container">
    <form role="form" method="post"  action="javascript:void(0);" id="filter-form">
        <h4 id="report-title"></h4>
        <div class="body">
            <div class="table">
                <!-- Common filter -->
                @Html.Partial("_BasicFilter")

                <!-- Search Button -->
                <br />
                <div class="row pull-right">
                    <div class="col-md-2 col-sm-2">
                        <button id="search-tg" type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
                <br /><br />
            </div> 
        </div>
    </form>
</div>
<br />
<div id="results-container">
    <h4 id="search-title"></h4>
    <br />
    <div class="row">
        <div class="tk-grid">
            <div id="my-reports-grid"></div>
        </div>
    </div>
</div>

<!-- Operation js -->
<script src="~/js/kendo/2017.1.223/kendo.web.min.js"></script>
<script src="~/js/kendo/2017.1.223/cultures/kendo.culture.en-CA.min.js"></script>
<script src="~/js/jquery.form.min.js"></script>
<!-- Used to export to excel -->
<script src="~/js/jszip.min.js"></script>
<!-- Load Pako ZLIB library to enable PDF compression -->
<script src="~/js/pako_deflate.min.js"></script>
<!-- Form js -->
<script src="~/js/ETFO/base.core.js"></script>
<script src="~/js/ETFO/ajax.update.progress.js"></script>
<script>
    // Basic filter Variables
    var urlLoadBasicStatusDropDowns = '@(Url.Action("LoadBasicStatusFilters", "MyReports", new object { }))';
    var urlLoadCategories = '@(Url.Action("LoadCategories", "MyReports", new object { }))';
    var urlLoadSubcategories = '@(Url.Action("LoadSubcategories", "MyReports", new object { }))';

    // Form Variables
    var urlSearch = '@(Url.Action("GetInstructorCourseList", "MyReports"))';
    var urlSearchAttendee = '@(Url.Action("GetCourseAttendees", "MyReports"))';
    var urlProxy = '@(Url.Action("KendoSave", "MyReports"))';

    $(document).ready(function ()
    {
        $("#myresults-menu").kendoMenu();
        $(".menu-instructors").addClass("k-state-selected")
        $(".menu-instructorcourselist").addClass("k-state-selected")
    });
</script>
<script src="~/Areas/MyReports/js/instructorCourseList.js"></script>
<script src="~/Areas/MyReports/js/basicfilter.js"></script>

ETFOPortal/Areas/MyReports/Views/MyReports/InstructorCourseListAttendance.cshtml
@using Adxstudio.Xrm.Web.Mvc.Html

<link rel="stylesheet" href="~/css/kendo/2017.1.223/kendo.common.min.css"/>
<link rel="stylesheet" href="~/css/kendo/2017.1.223/kendo.bootstrap.min.css" />

<!-- Menu -->
@Html.Partial("_Menu")

<div id="filter-container">
    <form role="form" method="post"  action="javascript:void(0);" id="filter-form">
        <h4 id="report-title"></h4>
        <div class="body">
            <div class="table">
                <!-- Common filter -->
                @Html.Partial("_BasicFilter")

                <!-- Search Button -->
                <br />
                <div class="row pull-right">
                    <div class="col-md-2 col-sm-2">
                        <button id="search-tg" type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
                <br /><br />
            </div> 
        </div>
    </form>
</div>
<br />

<div id="results-container">
    <h4 id="search-title"></h4>
    <br />
    <div class="row">
        <div class="tk-grid">
            <div id="my-reports-grid"></div>
        </div>
    </div>
</div>

<!-- Operation js -->
<script src="~/js/kendo/2017.1.223/kendo.web.min.js"></script>
<script src="~/js/kendo/2017.1.223/cultures/kendo.culture.en-CA.min.js"></script>
<script src="~/js/jquery.form.min.js"></script>
<!-- Used to export to excel -->
<script src="~/js/jszip.min.js"></script>
<!-- Load Pako ZLIB library to enable PDF compression -->
<script src="~/js/pako_deflate.min.js"></script>
<!-- Form js -->
<script src="~/js/ETFO/base.core.js"></script>
<script src="~/js/ETFO/ajax.update.progress.js"></script>
<script type="text/x-kendo-template" id="template">
    <div class="tabstrip">
        <ul>
            <li class="k-state-active">
                Attendees
            </li>
        </ul>
        <div>
            <div class="attendees"></div>
        </div>
        <div>
            <div class='attendees-details'>
                <ul>
                    <li><label>Number:</label>#= Number #</li>
                    <li><label>Name:</label>#= Name #</li>
                    <li><label>Mail:</label>#= Mail #</li>
                    <li><label>SchoolBoard:</label>#= SchoolBoard #</li>
                </ul>
            </div>
        </div>
    </div>
</script>
<script>
    // Basic filter Variables
    var urlLoadBasicStatusDropDowns = '@(Url.Action("LoadBasicStatusFilters", "MyReports", new object { }))';
    var urlLoadCategories = '@(Url.Action("LoadCategories", "MyReports", new object { }))';
    var urlLoadSubcategories = '@(Url.Action("LoadSubcategories", "MyReports", new object { }))';

    // Form Variables
    var urlSearch = '@(Url.Action("GetInstructorCourseListAttendance", "MyReports"))';
    var urlSearchAttendee = '@(Url.Action("GetCourseAttendance", "MyReports"))';
    var urlProxy = '@(Url.Action("KendoSave", "MyReports"))';

    $(document).ready(function ()
    {
        $("#myresults-menu").kendoMenu();
        $(".menu-instructors").addClass("k-state-selected")
        $(".menu-instructorcourselistAttendance").addClass("k-state-selected")
    });
</script>
<script src="~/Areas/MyReports/js/instructorcourselistAttendance.js"></script>
<script src="~/Areas/MyReports/js/basicfilter.js"></script>